// File generated by FlutterFire CLI & Firebase MCP configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your EventEase Firebase project (eventease-acd2b).
class DefaultFirebaseOptions {
  /// Detects whether live production Firebase credentials have been configured
  static bool get isLiveFirebaseConfigured {
    final key = currentPlatform.apiKey;
    return !key.contains('DemoKey') && !key.contains('Demo') && key.isNotEmpty;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJyRmAOpDMkkeQT9yECkxQfF8WY8wpwU',
    appId: '1:888183659719:web:c2b03e11c1abe692f532e2',
    messagingSenderId: '888183659719',
    projectId: 'eventease-acd2b',
    authDomain: 'eventease-acd2b.firebaseapp.com',
    storageBucket: 'eventease-acd2b.firebasestorage.app',
    measurementId: 'G-QGCWLNXE26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSa4gdjxE2Z3QFS9TiLNIY0pAPLSl6Zy8',
    appId: '1:888183659719:android:6ec5738cab8931baf532e2',
    messagingSenderId: '888183659719',
    projectId: 'eventease-acd2b',
    storageBucket: 'eventease-acd2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrXXkoP8XKoEbYI-kHUMk0rdwVDuso6Y',
    appId: '1:888183659719:ios:cc17b4c188569028f532e2',
    messagingSenderId: '888183659719',
    projectId: 'eventease-acd2b',
    storageBucket: 'eventease-acd2b.firebasestorage.app',
    iosBundleId: 'com.eventease.eventease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTrXXkoP8XKoEbYI-kHUMk0rdwVDuso6Y',
    appId: '1:888183659719:ios:cc17b4c188569028f532e2',
    messagingSenderId: '888183659719',
    projectId: 'eventease-acd2b',
    storageBucket: 'eventease-acd2b.firebasestorage.app',
    iosBundleId: 'com.eventease.eventease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzJyRmAOpDMkkeQT9yECkxQfF8WY8wpwU',
    appId: '1:888183659719:web:c2b03e11c1abe692f532e2',
    messagingSenderId: '888183659719',
    projectId: 'eventease-acd2b',
    authDomain: 'eventease-acd2b.firebaseapp.com',
    storageBucket: 'eventease-acd2b.firebasestorage.app',
    measurementId: 'G-QGCWLNXE26',
  );
}
