# Unused Podfile created to explicitly set platform deployment target for Flutter & CocoaPods
platform :ios, '15.5'

# CocoaPods analytics directive
install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
